### PR TITLE
New MotionNotReady codes and strings

### PR DESCRIPTION
**Pull request by jimmy-mcelwain**
MotionNotReady codes and strings have been added in to clarify error messages. Also changed wording on cycle mode to match what the user sees

### CODE REVIEW

**Comment by jimmy-mcelwain** [comment]
Required for https://github.com/Yaskawa-Global/motoros2/pull/265
Relevant to:
https://github.com/Yaskawa-Global/motoros2/issues/192 
and 
https://github.com/Yaskawa-Global/motoros2/issues/37

**Comment by ted-miller** [comment]
This looks fine. We'll keep this open until https://github.com/Yaskawa-Global/motoros2/pull/265 is fully resolved and we're clear on the process for merging this and keeping other repos in sync (https://github.com/Yaskawa-Global/motoros2_interfaces/discussions/18)

**Comment by jimmy-mcelwain** [comment]
Rebased on main after conflict with #23

**Review by gavanderhoorn — APPROVED** [review]
We can probably merge this, without Yaskawa-Global/motoros2#265 getting merged immediately.

After this is merged, we can cut a new release here, update `micro_ros_motoplus` and then fix CI over at `Yaskawa-Global/motoros2`.

**Comment by ted-miller** [comment]
> After this is merged, we can cut a new release here, update micro_ros_motoplus and then fix CI over at Yaskawa-Global/motoros2

PR for new release: https://github.com/Yaskawa-Global/motoros2_interfaces/pull/25

**Pull request merged**
