### PR TITLE
Motoros2 issue 203 cycle switch mode

### PR DESCRIPTION
**Pull request by yai-rosejo**
Added in an enum for when the cycle mode isn't set to continuous. 
Relates to [issue 203](https://github.com/Yaskawa-Global/motoros2/issues/203)

### CODE REVIEW

**Comment by ted-miller** [comment]
@yai-rosejo, when we were discussing, you mentioned you had an issue until you properly sourced these messages in your VM.

Was the issue that you forgot to source them entirely? Or was it that you were sourcing the old version of the messages?

As I think about this some more, I'm concerned about we enforce version compatibility.

**Comment by yai-rosejo** [comment]
I had forgot to source them entirely in my VM. After following this [ReadMe](https://github.com/yaskawa-global/motoros2_client_interface_dependencies), I was fine. I was also worried about version compatibility but the display in my VM worked without any modifications to that readme.
```
user@ROS2:~/colcon_ws$ ros2 service call /start_traj_mode motoros2_interfaces/srv/StartTrajMode
waiting for service to become available...
requester: making request: motoros2_interfaces.srv.StartTrajMode_Request()


response:
motoros2_interfaces.srv.StartTrajMode_Response(result_code=motoros2_interfaces.msg.MotionReadyEnum(value=115), message='Continuous cycle mode not set. Please set the cycle mode to continuous')

**Comment by gavanderhoorn** [comment]
The reason this works if because we're only using this message as a file to define some constants.

If we'd somehow embedded the `.msg` itself in the service response we'd have to version things.

But that's not what we're going, we're basically just setting an `int` to a value from the `enum`.

(this was why I set up this structure like this)

**Review by ted-miller — APPROVED** [review]
This is required for https://github.com/Yaskawa-Global/motoros2/pull/212

**Pull request merged**
